name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-security-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -E gosec
        version: latest
    - name: Run tests and generate coverage.out
      run: go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.out
