name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run gosec
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33
        args: -E gosec

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests and generate coverage.out
      run: go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to ccoverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
