name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-security-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -E gosec
        version: latest

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests and generate coverage.out
      run: go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to ccoverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
